window.QIGO_EMERGENCY_CATALOG = Object.freeze({
  official: [
    {
      id: "erss-112",
      icon: "112",
      title: "Police + Ambulance + Fire",
      subtitle: "भारत सरकार ERSS · Pan-India emergency",
      actionLabel: "112 पर call करें",
      href: "tel:112",
      source: "https://112.gov.in/",
      verified: true,
    },
    {
      id: "ambulance-108",
      icon: "108",
      title: "State ambulance service",
      subtitle: "Availability राज्य के अनुसार बदल सकती है",
      actionLabel: "108 try करें",
      href: "tel:108",
      source: "https://112.gov.in/about",
      verified: true,
    },
  ],
  nearby: [
    {
      id: "trauma-hospital",
      icon: "H",
      title: "Nearest hospital / trauma centre",
      subtitle: "Emergency department और route",
      query: "emergency hospital trauma centre",
      actionLabel: "Map पर देखें",
    },
    {
      id: "police-station",
      icon: "P",
      title: "Nearest police station",
      subtitle: "Accident reporting और local assistance",
      query: "police station",
      actionLabel: "Map पर देखें",
    },
    {
      id: "tow-service",
      icon: "T",
      title: "Towing / roadside recovery",
      subtitle: "Vehicle को सुरक्षित जगह पहुँचाने के लिए",
      query: "car towing roadside assistance",
      actionLabel: "Nearby खोजें",
    },
    {
      id: "safe-taxi",
      icon: "C",
      title: "Taxi / safe transport",
      subtitle: "अगर medical emergency नहीं है और यात्रा सुरक्षित है",
      query: "taxi cab service",
      actionLabel: "Nearby खोजें",
    },
    {
      id: "body-shop",
      icon: "W",
      title: "Workshop / body repair",
      subtitle: "Company और damage के अनुसार agency search",
      query: "authorised car body repair workshop",
      actionLabel: "Agency खोजें",
    },
    {
      id: "insurance-help",
      icon: "I",
      title: "Insurance claim help",
      subtitle: "Policy helpline, survey और cashless garage",
      query: "motor insurance claim assistance",
      actionLabel: "Nearby help",
    },
  ],
  vehicleBrands: [
    "Maruti Suzuki",
    "Hyundai",
    "Tata Motors",
    "Mahindra",
    "Toyota",
    "Honda",
    "Kia",
    "MG Motor",
    "Skoda",
    "Volkswagen",
    "Renault",
    "Nissan",
    "Other / Not sure",
  ],
  dangerSignals: [
    "कोई घायल, बेहोश या फँसा हुआ है",
    "तेज bleeding या सांस लेने में दिक्कत है",
    "धुआँ, आग, fuel smell या fluid leak है",
    "Airbags खुले हैं या vehicle बुरी तरह मुड़ी है",
    "Road/traffic के बीच immediate danger है",
  ],
});
